Update eclipseOS-setup

diff --git a/bin/eclipseOS-setup b/bin/eclipseOS-setup
--- a/bin/eclipseOS-setup
+++ b/bin/eclipseOS-setup
@@ -26,10 +26,9 @@ for package in "${AUR_PACKAGES[@]}"; do
 done
 
 echo
-echo "-> Installing github-desktop (NODE_VERSION=20.0)..."
-if ! NODE_VERSION=20.0 yay -S --noconfirm github-desktop; then
-  echo "!! Failed to install github-desktop"
-  FAILED_PACKAGES+=("github-desktop")
+echo "-> Installing github-desktop-bin..."
+yay -S --noconfirm github-desktop-bin || echo "!! Failed to install github-desktop"
+FAILED_PACKAGES+=("github-desktop")
 fi
 
 echo
